% Coriolis
clc
syms x1(t) L x2(t) x3(t) x4(t) x5(t) x6(t) dx1 dx2 dx3 dx4 dx5 dx6 real

m_asta = 0.05;
m_telaio = 0.50;
m_Rx = 0.50;
m_Rz = m_Rx;
m_Ry = m_Rx;
R = 0.10;
L_asta = 0.15;
L = 2*L_asta;
%% 
B_N =  [
                                                                                                                                                                                                                                                                                                                                                                                                                                                           (m_Rx*(L^2*cos(2*x2) + L^2 + 2*R^2))/2 + (m_telaio*(250*L^2 - 250*L^2*sin(x2)^2 + 1))/250 + (m_asta*(3*L^2 - 3*L^2*sin(x2)^2 + 4*L_asta^2))/48 - L^2*m_Ry*(sin(x2)^2 - 1) - L^2*m_Rz*(sin(x2)^2 - 1),                                                                                                                         0, (m_telaio*sin(x2))/250 + (L_asta^2*m_asta*sin(x2))/12 + R^2*m_Rx*(cos(x4)*(cos(x4)*(cos(x1)*sin(x3) + cos(x3)*sin(x1)*sin(x2)) + cos(x2)*sin(x1)*sin(x4))*(cos(x3)*sin(x1) + cos(x1)*sin(x2)*sin(x3)) - (cos(x1)*cos(x3) - sin(x1)*sin(x2)*sin(x3))*(sin(x1)*sin(x3) - cos(x1)*cos(x3)*sin(x2)) + sin(x4)*(sin(x4)*(cos(x1)*sin(x3) + cos(x3)*sin(x1)*sin(x2)) - cos(x2)*cos(x4)*sin(x1))*(cos(x3)*sin(x1) + cos(x1)*sin(x2)*sin(x3)))*((cos(x4)*(cos(x1)*sin(x3) + cos(x3)*sin(x1)*sin(x2)) + cos(x2)*sin(x1)*sin(x4))^2 + (sin(x4)*(cos(x1)*sin(x3) + cos(x3)*sin(x1)*sin(x2)) - cos(x2)*cos(x4)*sin(x1))^2 + (cos(x1)*cos(x3) - sin(x1)*sin(x2)*sin(x3))^2),                                                                                                                                               -R^2*m_Rx*cos(x2)*sin(x3)*((cos(x4)*(cos(x1)*sin(x3) + cos(x3)*sin(x1)*sin(x2)) + cos(x2)*sin(x1)*sin(x4))^2 + (sin(x4)*(cos(x1)*sin(x3) + cos(x3)*sin(x1)*sin(x2)) - cos(x2)*cos(x4)*sin(x1))^2 + (cos(x1)*cos(x3) - sin(x1)*sin(x2)*sin(x3))^2),                                                                     0,                                0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              0, m_Rz*(L^2 + R^2*sin(x1)^2) + (m_telaio*(250*L^2 + 1))/250 + L^2*m_Rx + (L^2*m_asta)/16 + m_Ry*(L^2 - R^2*sin(x1)^2 + R^2),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     -R^2*cos(x1)*cos(x2)*sin(x1)*(m_Ry - m_Rz),                                                                                                                                                                                                                                                                                                                                                                                               0,          R^2*m_Ry*cos(x1)*(cos(x1)*sin(x3) + cos(x3)*sin(x1)*sin(x2)), R^2*m_Rz*cos(x1)*cos(x2)*sin(x1);
 (m_telaio*sin(x2))/250 + (L_asta^2*m_asta*sin(x2))/12 + R^2*m_Rx*(cos(x4)*(cos(x4)*(cos(x1)*sin(x3) + cos(x3)*sin(x1)*sin(x2)) + cos(x2)*sin(x1)*sin(x4))*(cos(x3)*sin(x1) + cos(x1)*sin(x2)*sin(x3)) - (cos(x1)*cos(x3) - sin(x1)*sin(x2)*sin(x3))*(sin(x1)*sin(x3) - cos(x1)*cos(x3)*sin(x2)) + sin(x4)*(sin(x4)*(cos(x1)*sin(x3) + cos(x3)*sin(x1)*sin(x2)) - cos(x2)*cos(x4)*sin(x1))*(cos(x3)*sin(x1) + cos(x1)*sin(x2)*sin(x3)))*((cos(x4)*(cos(x1)*sin(x3) + cos(x3)*sin(x1)*sin(x2)) + cos(x2)*sin(x1)*sin(x4))^2 + (sin(x4)*(cos(x1)*sin(x3) + cos(x3)*sin(x1)*sin(x2)) - cos(x2)*cos(x4)*sin(x1))^2 + (cos(x1)*cos(x3) - sin(x1)*sin(x2)*sin(x3))^2),                                                                                -R^2*cos(x1)*cos(x2)*sin(x1)*(m_Ry - m_Rz),                                                                                                                                                                                                                                                                                                                                           m_telaio/250 + (L_asta^2*m_asta)/24 + (R^2*m_Rx)/2 + (R^2*m_Ry)/4 + (R^2*m_Rz)/4 - (L_asta^2*m_asta*cos(2*x2))/24 - (R^2*m_Rx*cos(2*x2))/2 - (R^2*m_Ry*cos(2*x1))/4 + (R^2*m_Ry*cos(2*x2))/4 + (R^2*m_Rz*cos(2*x1))/4 + (R^2*m_Rz*cos(2*x2))/4 - (R^2*m_Ry*cos(2*x1)*cos(2*x2))/4 + (R^2*m_Rz*cos(2*x1)*cos(2*x2))/4, -R^2*m_Rx*cos(x2)*sin(x3)*(cos(x4)*(cos(x4)*(cos(x1)*sin(x3) + cos(x3)*sin(x1)*sin(x2)) + cos(x2)*sin(x1)*sin(x4))*(cos(x3)*sin(x1) + cos(x1)*sin(x2)*sin(x3)) - (cos(x1)*cos(x3) - sin(x1)*sin(x2)*sin(x3))*(sin(x1)*sin(x3) - cos(x1)*cos(x3)*sin(x2)) + sin(x4)*(sin(x4)*(cos(x1)*sin(x3) + cos(x3)*sin(x1)*sin(x2)) - cos(x2)*cos(x4)*sin(x1))*(cos(x3)*sin(x1) + cos(x1)*sin(x2)*sin(x3))), -R^2*m_Ry*cos(x2)*sin(x1)*(cos(x1)*sin(x3) + cos(x3)*sin(x1)*sin(x2)),     R^2*m_Rz*cos(x1)^2*cos(x2)^2;
                                                                                                                                                                                                                                                                                                                                                                                                              -R^2*m_Rx*cos(x2)*sin(x3)*((cos(x4)*(cos(x1)*sin(x3) + cos(x3)*sin(x1)*sin(x2)) + cos(x2)*sin(x1)*sin(x4))^2 + (sin(x4)*(cos(x1)*sin(x3) + cos(x3)*sin(x1)*sin(x2)) - cos(x2)*cos(x4)*sin(x1))^2 + (cos(x1)*cos(x3) - sin(x1)*sin(x2)*sin(x3))^2),                                                                                                                         0,                                                                                                                                                                                                                                                                -R^2*m_Rx*cos(x2)*sin(x3)*(cos(x4)*(cos(x4)*(cos(x1)*sin(x3) + cos(x3)*sin(x1)*sin(x2)) + cos(x2)*sin(x1)*sin(x4))*(cos(x3)*sin(x1) + cos(x1)*sin(x2)*sin(x3)) - (cos(x1)*cos(x3) - sin(x1)*sin(x2)*sin(x3))*(sin(x1)*sin(x3) - cos(x1)*cos(x3)*sin(x2)) + sin(x4)*(sin(x4)*(cos(x1)*sin(x3) + cos(x3)*sin(x1)*sin(x2)) - cos(x2)*cos(x4)*sin(x1))*(cos(x3)*sin(x1) + cos(x1)*sin(x2)*sin(x3))),                                                                                                                                                                                                                                                                                                                                                                    R^2*m_Rx*cos(x2)^2*sin(x3)^2,                                                                     0,                                0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              0,                                                              R^2*m_Ry*cos(x1)*(cos(x1)*sin(x3) + cos(x3)*sin(x1)*sin(x2)),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          -R^2*m_Ry*cos(x2)*sin(x1)*(cos(x1)*sin(x3) + cos(x3)*sin(x1)*sin(x2)),                                                                                                                                                                                                                                                                                                                                                                                               0,                R^2*m_Ry*(cos(x1)*sin(x3) + cos(x3)*sin(x1)*sin(x2))^2,                                0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               0,                                                              R^2*m_Ry*cos(x1)*(cos(x1)*sin(x3) + cos(x3)*sin(x1)*sin(x2)),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          -R^2*m_Ry*cos(x2)*sin(x1)*(cos(x1)*sin(x3) + cos(x3)*sin(x1)*sin(x2)),                                                                                                                                                                                                                                                                                                                                                                                               0,                R^2*m_Ry*(cos(x1)*sin(x3) + cos(x3)*sin(x1)*sin(x2))^2,                                0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              0,                                                                                          R^2*m_Rz*cos(x1)*cos(x2)*sin(x1),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   R^2*m_Rz*cos(x1)^2*cos(x2)^2,                                                                                                                                                                                                                                                                                                                                                                                               0,                                                                     0,     R^2*m_Rz*cos(x1)^2*cos(x2)^2];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
 %%
 
 B_N1 = B_N;
 
%% 
dB_N1 = diff(B_N1,t);
dB_N1 = subs(dB_N1, diff(x1(t), t)  ,'dx1');
dB_N1 = subs(dB_N1, diff(x2(t), t)  ,'dx2');
dB_N1 = subs(dB_N1, diff(x3(t), t)  ,'dx3');
dB_N1 = subs(dB_N1, diff(x4(t), t) ,'dx4');
dB_N1 = subs(dB_N1, diff(x5(t), t)  ,'dx5');
dB_N1 = subs(dB_N1, diff(x6(t), t) ,'dx6');


 