function B = gen_dinamica_B(q,parameter)

x1 = q(1);
x2 = q(2);
x3 = q(3);
x4 = q(4);
x5 = q(5);
m_r = parameter(1);
m_c = parameter(2);
R_r = parameter(3);
L = parameter(4);
a = parameter(5);

B = [ (m_r*(4*L^2*cos(x2)^2 + 4*R_r^2*cos(x2)^2 + a^2 - 4*R_r^2*cos(x2)^2*cos(x3)^2 - a^2*cos(x2)^2*cos(x3)^2 - 4*L*a*cos(x2)*cos(x3)*sin(x2)))/4 + (m_r*(4*L^2*cos(x2)^2 - a^2*cos(x2)^2 + a^2 + 4*R_r^2*cos(x2)^2*cos(x3)^2 + a^2*cos(x2)^2*cos(x3)^2 + 4*L*a*cos(x2)*sin(x2)*sin(x3)))/4 + (m_c*(12*L^2*cos(x2)^2 - 3*a^2*cos(x2)^2 + 8*a^2 + 6*a^2*cos(x2)^2*cos(x3)*sin(x3) - 12*L*a*cos(x2)*cos(x3)*sin(x2) + 12*L*a*cos(x2)*sin(x2)*sin(x3)))/12, (m_r*cos(x3)*(4*cos(x2)*sin(x3)*R_r^2 + cos(x2)*sin(x3)*a^2 - 2*L*sin(x2)*a))/4 - (m_r*sin(x3)*(4*cos(x2)*cos(x3)*R_r^2 + cos(x2)*cos(x3)*a^2 + 2*L*sin(x2)*a))/4 - (a*m_c*(cos(x3) + sin(x3))*(2*L*sin(x2) + a*cos(x2)*cos(x3) - a*cos(x2)*sin(x3)))/4, (a*((a*m_r*sin(x2))/2 + L*m_r*cos(x2)*sin(x3)))/2 + (a*m_c*(4*a*sin(x2) - 3*L*cos(x2)*cos(x3) + 3*L*cos(x2)*sin(x3)))/6 + (a*m_r*(a*sin(x2) - 2*L*cos(x2)*cos(x3)))/4, (m_r*cos(x2)*cos(x3)*(4*L^2 + 4*R_r^2 + a^2))/4, -(m_r*cos(x2)*sin(x3)*(4*L^2 + 4*R_r^2 + a^2))/4;
                                                                                                                                                                                           (m_r*cos(x3)*(4*cos(x2)*sin(x3)*R_r^2 + cos(x2)*sin(x3)*a^2 - 2*L*sin(x2)*a))/4 - (m_r*sin(x3)*(4*cos(x2)*cos(x3)*R_r^2 + cos(x2)*cos(x3)*a^2 + 2*L*sin(x2)*a))/4 - (a*m_c*(cos(x3) + sin(x3))*(2*L*sin(x2) + a*cos(x2)*cos(x3) - a*cos(x2)*sin(x3)))/4,                                                                                                 (m_c*(12*L^2 - 3*a^2*sin(2*x3) + 5*a^2))/12 + (m_r*(4*R_r^2*cos(x3)^2 + a^2*cos(x3)^2 + 4*L^2))/4 + (m_r*(4*R_r^2*sin(x3)^2 + a^2*sin(x3)^2 + 4*L^2))/4,                                                                                      - (L*a*m_r*cos(x3))/2 - (L*a*m_r*sin(x3))/2 - (2^(1/2)*L*a*m_c*sin(x3 + pi/4))/2,         (m_r*sin(x3)*(4*L^2 + 4*R_r^2 + a^2))/4,          (m_r*cos(x3)*(4*L^2 + 4*R_r^2 + a^2))/4;
                                                                                                                                                                                                                                                                                   (a*m_c*(4*a*sin(x2) - 3*L*cos(x2)*cos(x3) + 3*L*cos(x2)*sin(x3)))/6 + (a*m_r*(a*sin(x2) - 2*L*cos(x2)*cos(x3)))/4 + (a*m_r*(a*sin(x2) + 2*L*cos(x2)*sin(x3)))/4,                                                                                                                                                                        - (L*a*m_r*cos(x3))/2 - (L*a*m_r*sin(x3))/2 - (2^(1/2)*L*a*m_c*sin(x3 + pi/4))/2,                                                                                                                                           (2*a^2*m_c)/3 + (a^2*m_r)/2,                                               0,                                                0;
                                                                                                                                                                                                                                                                                                                                                                                                   (m_r*cos(x2)*cos(x3)*(4*L^2 + 4*R_r^2 + a^2))/4,                                                                                                                                                                                                                 (m_r*sin(x3)*(4*L^2 + 4*R_r^2 + a^2))/4,                                                                                                                                                                     0,                 (m_r*(4*L^2 + 4*R_r^2 + a^2))/4,                                                0;
                                                                                                                                                                                                                                                                                                                                                                                                  -(m_r*cos(x2)*sin(x3)*(4*L^2 + 4*R_r^2 + a^2))/4,                                                                                                                                                                                                                 (m_r*cos(x3)*(4*L^2 + 4*R_r^2 + a^2))/4,                                                                                                                                                                     0,                                               0,                  (m_r*(4*L^2 + 4*R_r^2 + a^2))/4];
                                                                                                                                                                                                                                                                                                                                                                                              
end